# Generated by Django 5.0.14 on 2025-08-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='patient',
            field=models.CharField(max_length=255),
        ),
    ]
